---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: bluebuild-custom
description: My custom Fedora KDE bootc image.

base-image: ghcr.io/blue-build/base-images/fedora-kinoite
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - cowsay

  - type: script
    scripts:
      - create-admin.sh

  - type: systemd
    system:
      enabled:
        - reset-guest.service
