---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: ${{ vars.IMAGE_NAME }}
description: My custom Fedora KDE bootc image.

base-image: ghcr.io/blue-build/base-images/fedora-kinoite
image-version: latest

modules:
  - type: dnf
    install:
      packages:
        - cowsay

